/* 晓的工作台：扩展数据云同步 v1 */
(function(){
const EXTRA_KEYS=['xiao_study_hubs_v2','xiao_psychology_hub_v1','xiao_weekly_reflections','xiao_current_affairs_v1'];
function packExtras(){let out={};EXTRA_KEYS.forEach(k=>{let v=localStorage.getItem(k);if(v!==null){try{out[k]=JSON.parse(v)}catch{}}});return out}
function applyExtras(extras){if(!extras||typeof extras!=='object')return;EXTRA_KEYS.forEach(k=>{if(Object.prototype.hasOwnProperty.call(extras,k))localStorage.setItem(k,JSON.stringify(extras[k]))})}
window.packWorkbenchCloud=function(){return{core:data,extras:packExtras(),schema:2}}
window.applyWorkbenchCloud=function(payload){if(!payload)return;if(payload.core){data=payload.core;localStorage.setItem('xiao_workbench_v4',JSON.stringify(data));applyExtras(payload.extras)}else{data=payload;localStorage.setItem('xiao_workbench_v4',JSON.stringify(data))}}
window.pushCloud=async function(showMsg=false){if(!auth?.access_token)return;syncing=true;cloudBtn.textContent='☁ 同步中';try{let payload=packWorkbenchCloud(),r=await cloudFetch('/rest/v1/workbench_state?on_conflict=user_id',{method:'POST',headers:{'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:auth.user.id,data:payload,updated_at:new Date().toISOString()})});if(!r.ok)throw Error((await r.text())||'同步失败');cloudBtn.textContent='☁ 已同步';if(showMsg)accountPanel('同步完成，学习扩展数据也已上传')}catch(err){cloudBtn.textContent='☁ 同步失败';if(showMsg)accountPanel('同步失败：'+err.message)}finally{syncing=false}};
window.pullCloud=async function(){let r=await cloudFetch('/rest/v1/workbench_state?select=data,updated_at&user_id=eq.'+encodeURIComponent(auth.user.id));if(!r.ok)throw Error(await r.text());let rows=await r.json(),row=rows[0]||null;if(row?.data?.schema===2&&row.data.core)return{...row,data:row.data.core,_extras:row.data.extras||{}};return row};
window.firstCloudSync=async function(){if(!auth?.access_token)return;cloudBtn.textContent='☁ 连接中';try{let row=await window.pullCloud();if(row?.data){data=row.data;localStorage.setItem('xiao_workbench_v4',JSON.stringify(data));if(row._extras)applyExtras(row._extras);if(typeof render==='function')render();cloudBtn.textContent='☁ 已同步'}else await window.pushCloud(false)}catch(err){cloudBtn.textContent='☁ 同步失败'}};
window.syncNow=async function(showMsg=false){try{let row=await window.pullCloud();if(row?.data){data=row.data;localStorage.setItem('xiao_workbench_v4',JSON.stringify(data));if(row._extras)applyExtras(row._extras);if(typeof render==='function')render()}await window.pushCloud(showMsg)}catch(err){if(showMsg)accountPanel('同步失败：'+err.message)}};
})();