/* 晓的工作台：扩展数据云同步 v3，多设备冲突保护 */
(function(){
const EXTRA_KEYS=['xiao_study_hubs_v2','xiao_psychology_hub_v1','xiao_weekly_reflections','xiao_current_affairs_v1'],META='xiao_cloud_sync_meta_v2';
function read(k,f=null){try{let v=localStorage.getItem(k);return v===null?f:JSON.parse(v)}catch{return f}}function meta(){return read(META,{})||{}}function writeMeta(x){localStorage.setItem(META,JSON.stringify({...meta(),...x}))}function extras(){let o={};EXTRA_KEYS.forEach(k=>{let v=read(k,undefined);if(v!==undefined)o[k]=v});return o}function hasExtras(){return EXTRA_KEYS.some(k=>localStorage.getItem(k)!==null)}function applyExtras(o,preserve=false){if(!o)return;EXTRA_KEYS.forEach(k=>{if(!(k in o))return;if(preserve&&localStorage.getItem(k)!==null)return;localStorage.setItem(k,JSON.stringify(o[k]))})}function localStamp(){return +meta().localChangedAt||0}function cloudStamp(row){return Date.parse(row?.updated_at||0)||0}function touch(){writeMeta({localChangedAt:Date.now()})}
// 扩展模块写 localStorage 时没有统一 save 入口，用 storage setter 记录本机变更时间。
const rawSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){rawSet.call(this,k,v);if(this===localStorage&&(k==='xiao_workbench_v4'||EXTRA_KEYS.includes(k))&&k!==META)rawSet.call(this,META,JSON.stringify({...meta(),localChangedAt:Date.now()}))};
window.packWorkbenchCloud=function(){return{core:data,extras:extras(),schema:3,clientUpdatedAt:new Date().toISOString()}};
window.pushCloud=async function(showMsg=false){if(!auth?.access_token)return;syncing=true;cloudBtn.textContent='☁ 同步中';try{let payload=packWorkbenchCloud(),r=await cloudFetch('/rest/v1/workbench_state?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({user_id:auth.user.id,data:payload,updated_at:new Date().toISOString()})});if(!r.ok)throw Error((await r.text())||'同步失败');let rows=await r.json(),stamp=cloudStamp(rows[0]);writeMeta({schema:3,lastSync:Date.now(),lastCloudUpdatedAt:stamp,localChangedAt:0});cloudBtn.textContent='☁ 已同步';if(showMsg)accountPanel('同步完成，学习扩展数据也已上传')}catch(err){cloudBtn.textContent='☁ 同步失败';if(showMsg)accountPanel('同步失败：'+err.message)}finally{syncing=false}};
window.pullCloud=async function(){let r=await cloudFetch('/rest/v1/workbench_state?select=data,updated_at&user_id=eq.'+encodeURIComponent(auth.user.id));if(!r.ok)throw Error(await r.text());let rows=await r.json(),row=rows[0]||null;if(row?.data?.schema>=2&&row.data.core)return{...row,data:row.data.core,_extras:row.data.extras||{},_schema:row.data.schema};return row?{...row,_schema:1}:null};
function applyRow(row,preserve=false){data=row.data;rawSet.call(localStorage,'xiao_workbench_v4',JSON.stringify(data));if(row._extras)applyExtras(row._extras,preserve);writeMeta({schema:3,lastSync:Date.now(),lastCloudUpdatedAt:cloudStamp(row),localChangedAt:0});if(typeof render==='function')render()}
async function resolveSync(showMsg=false,first=false){let row=await pullCloud();if(!row?.data){await pushCloud(showMsg);return}let m=meta(),localDirty=localStamp()>0,remoteNew=cloudStamp(row)>(+m.lastCloudUpdatedAt||0),firstMigration=!m.schema;
if(firstMigration&&row._schema===1&&hasExtras()){data=row.data;rawSet.call(localStorage,'xiao_workbench_v4',JSON.stringify(data));await pushCloud(showMsg);return}
if(firstMigration&&row._schema>=2&&hasExtras()){applyRow(row,true);await pushCloud(showMsg);return}
if(localDirty&&remoteNew){cloudBtn.textContent='☁ 有冲突';if(showMsg)accountPanel('检测到另一台设备和本机都有新修改。为保护数据，已暂停自动覆盖。请先导出本机备份，再选择保留云端或本机版本。');return}
if(remoteNew&&!localDirty){applyRow(row,false);cloudBtn.textContent='☁ 已同步';return}
if(localDirty&&!remoteNew){await pushCloud(showMsg);return}
if(first)applyRow(row,false);else cloudBtn.textContent='☁ 已同步'}
window.firstCloudSync=async function(){if(!auth?.access_token)return;cloudBtn.textContent='☁ 连接中';try{await resolveSync(false,true)}catch(e){cloudBtn.textContent='☁ 同步失败'}};
window.syncNow=async function(showMsg=false){try{await resolveSync(showMsg,false)}catch(e){if(showMsg)accountPanel('同步失败：'+e.message)}};
window.cloudKeepLocal=async function(){await pushCloud(true)};window.cloudKeepRemote=async function(){let row=await pullCloud();if(row?.data){applyRow(row,false);accountPanel('已保留云端版本')}};
})();