/* 晓的工作台：扩展数据云同步 v4，多设备冲突处理界面 */
(function(){
const EXTRA_KEYS=['xiao_study_hubs_v2','xiao_psychology_hub_v1','xiao_weekly_reflections','xiao_current_affairs_v1'],META='xiao_cloud_sync_meta_v2';let pendingConflict=null;
function read(k,f=null){try{let v=localStorage.getItem(k);return v===null?f:JSON.parse(v)}catch{return f}}function meta(){return read(META,{})||{}}function writeMeta(x){localStorage.setItem(META,JSON.stringify({...meta(),...x}))}function extras(){let o={};EXTRA_KEYS.forEach(k=>{let v=read(k,undefined);if(v!==undefined)o[k]=v});return o}function hasExtras(){return EXTRA_KEYS.some(k=>localStorage.getItem(k)!==null)}function applyExtras(o,preserve=false){if(!o)return;EXTRA_KEYS.forEach(k=>{if(!(k in o))return;if(preserve&&localStorage.getItem(k)!==null)return;rawSet.call(localStorage,k,JSON.stringify(o[k]))})}function localStamp(){return +meta().localChangedAt||0}function cloudStamp(row){return Date.parse(row?.updated_at||0)||0}function fmt(n){if(!n)return'暂无记录';try{return new Date(n).toLocaleString('zh-CN',{hour12:false})}catch{return'未知'}}
const rawSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){rawSet.call(this,k,v);if(this===localStorage&&(k==='xiao_workbench_v4'||EXTRA_KEYS.includes(k))&&k!==META)rawSet.call(this,META,JSON.stringify({...meta(),localChangedAt:Date.now()}))};
window.packWorkbenchCloud=function(){return{core:data,extras:extras(),schema:4,clientUpdatedAt:new Date().toISOString()}};
window.pushCloud=async function(showMsg=false){if(!auth?.access_token)return;syncing=true;cloudBtn.textContent='☁ 同步中';try{let r=await cloudFetch('/rest/v1/workbench_state?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({user_id:auth.user.id,data:packWorkbenchCloud(),updated_at:new Date().toISOString()})});if(!r.ok)throw Error((await r.text())||'同步失败');let rows=await r.json(),stamp=cloudStamp(rows[0]);writeMeta({schema:4,lastSync:Date.now(),lastCloudUpdatedAt:stamp,localChangedAt:0});pendingConflict=null;cloudBtn.textContent='☁ 已同步';if(showMsg)accountPanel('同步完成，学习扩展数据也已上传')}catch(err){cloudBtn.textContent='☁ 同步失败';if(showMsg)accountPanel('同步失败：'+err.message)}finally{syncing=false}};
window.pullCloud=async function(){let r=await cloudFetch('/rest/v1/workbench_state?select=data,updated_at&user_id=eq.'+encodeURIComponent(auth.user.id));if(!r.ok)throw Error(await r.text());let rows=await r.json(),row=rows[0]||null;if(row?.data?.schema>=2&&row.data.core)return{...row,data:row.data.core,_extras:row.data.extras||{},_schema:row.data.schema};return row?{...row,_schema:1}:null};
function applyRow(row,preserve=false){data=row.data;rawSet.call(localStorage,'xiao_workbench_v4',JSON.stringify(data));if(row._extras)applyExtras(row._extras,preserve);writeMeta({schema:4,lastSync:Date.now(),lastCloudUpdatedAt:cloudStamp(row),localChangedAt:0});pendingConflict=null;if(typeof render==='function')render()}
window.openCloudConflict=function(){let row=pendingConflict,m=meta();if(!row){accountPanel('当前没有待处理的同步冲突');return}show(`<h3>☁️ 同步冲突</h3><div class="muted">检测到这台设备和云端都有新的学习记录。请选择要保留的版本。</div><div class="node"><b>📱 本机版本</b><div class="muted" style="margin-top:5px">最后修改：${fmt(localStamp())}</div><div style="margin-top:7px">保留后会把当前手机上的任务、教综、心理学等记录上传到云端。</div></div><div class="node"><b>☁️ 云端版本</b><div class="muted" style="margin-top:5px">最后修改：${fmt(cloudStamp(row))}</div><div style="margin-top:7px">使用后会用云端记录替换这台设备当前的工作台数据。</div></div><div class="muted" style="margin:10px 0">建议先使用“数据备份与恢复”导出本机备份，再决定。</div><button class="btn" style="width:100%" onclick="cloudKeepLocal()">保留本机并上传</button><button class="mini" style="width:100%;margin-top:8px" onclick="cloudKeepRemote()">使用云端版本</button><button class="mini" style="width:100%;margin-top:8px" onclick="closeM()">暂不处理</button>`)};
async function resolveSync(showMsg=false,first=false){let row=await pullCloud();if(!row?.data){await pushCloud(showMsg);return}let m=meta(),localDirty=localStamp()>0,remoteNew=cloudStamp(row)>(+m.lastCloudUpdatedAt||0),firstMigration=!m.schema;if(firstMigration&&row._schema===1&&hasExtras()){data=row.data;rawSet.call(localStorage,'xiao_workbench_v4',JSON.stringify(data));await pushCloud(showMsg);return}if(firstMigration&&row._schema>=2&&hasExtras()){applyRow(row,true);await pushCloud(showMsg);return}if(localDirty&&remoteNew){pendingConflict=row;cloudBtn.textContent='☁ 有冲突';cloudBtn.onclick=openCloudConflict;if(showMsg)openCloudConflict();return}if(remoteNew&&!localDirty){applyRow(row,false);cloudBtn.textContent='☁ 已同步';return}if(localDirty&&!remoteNew){await pushCloud(showMsg);return}if(first)applyRow(row,false);else cloudBtn.textContent='☁ 已同步'}
window.firstCloudSync=async function(){if(!auth?.access_token)return;cloudBtn.textContent='☁ 连接中';try{await resolveSync(false,true)}catch(e){cloudBtn.textContent='☁ 同步失败'}};window.syncNow=async function(showMsg=false){try{await resolveSync(showMsg,false)}catch(e){if(showMsg)accountPanel('同步失败：'+e.message)}};
window.cloudKeepLocal=async function(){if(typeof exportWorkbenchData==='function'){}cloudBtn.onclick=()=>syncNow(true);await pushCloud(true);closeM()};window.cloudKeepRemote=async function(){let row=pendingConflict||await pullCloud();if(row?.data){applyRow(row,false);cloudBtn.onclick=()=>syncNow(true);closeM();accountPanel('已使用云端版本')}};
})();
