/* 晓的工作台：每日时政前端模块 */
(function(){
  let affairs=[];const favKey='xiao_affairs_favorites',sourceKey='xiao_affairs_sources';
  const defaults=[{name:'中国政府网',type:'官方',enabled:true},{name:'新华社/新华网',type:'官方',enabled:true},{name:'国务院部门',type:'官方',enabled:true},{name:'人民日报',type:'官方',enabled:true}];
  function favorites(){try{return JSON.parse(localStorage.getItem(favKey)||'[]')}catch{return []}}function sources(){try{return JSON.parse(localStorage.getItem(sourceKey)||'null')||defaults}catch{return defaults}}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function score(x){if(x.score)return Math.max(1,Math.min(5,+x.score));let t=(x.title||'')+' '+(x.summary||''),n=2;if(/习近平|中共中央|国务院|全国人大|全国政协|重要会议|条例|规划|意见/.test(t))n+=2;if(/经济|就业|教育|科技|人工智能|民生|生态|法治|外交|改革|新质生产力/.test(t))n+=1;return Math.min(5,n)}
  function stars(x){let n=score(x);return '★'.repeat(n)+'☆'.repeat(5-n)}
  function affairCard(x,full=false){let fav=favorites().includes(x.id);return `<div class="node"><div class="head"><div class="txt">${esc(x.title)}</div><button class="mini" onclick="toggleAffairFav('${esc(x.id)}')">${fav?'★':'☆'}</button></div><div class="muted" style="margin:5px 0">${esc(x.date||'')} · ${esc(x.category||'时政')} · ${esc(x.source||'权威来源')}</div><div style="margin:5px 0"><b>${stars(x)}</b> <span class="muted">考试价值 ${score(x)}/5</span></div><div style="line-height:1.65">${esc(x.summary||'')}</div>${full?`<div class="chips"><span class="chip">行测常识</span><span class="chip">申论素材</span></div>${x.exam_point?`<div style="margin-top:10px"><b>考点：</b>${esc(x.exam_point)}</div>`:''}${x.essay_material?`<div style="margin-top:8px"><b>申论积累：</b>${esc(x.essay_material)}</div>`:''}${x.url?`<div style="margin-top:10px"><a href="${esc(x.url)}" target="_blank" rel="noopener">查看权威原文</a></div>`:''}`:''}</div>`}
  window.toggleAffairFav=function(id){let f=favorites(),i=f.indexOf(id);i>=0?f.splice(i,1):f.push(id);localStorage.setItem(favKey,JSON.stringify(f));render();renderAffairsPage()};
  window.currentCard=function(){let today=new Date().toLocaleDateString('sv-SE'),items=affairs.filter(x=>x.date===today).sort((a,b)=>score(b)-score(a));if(!items.length)items=[...affairs].sort((a,b)=>score(b)-score(a)).slice(0,3);return `<div class="card"><h3>📰 公务员 · 今日时政</h3>${items.length?items.slice(0,3).map(x=>affairCard(x,false)).join(''):'<div class="muted">今日时政数据正在准备中。自动更新后会在这里出现。</div>'}<div class="row"><button class="mini" onclick="openAffairs()">查看时政库</button><button class="mini" onclick="openAffairSources()">来源管理</button></div></div>`};
  window.openAffairs=function(){show(`<h3>📰 每日时政</h3><div class="muted">优先看 4～5 星内容。按日期积累行测常识与申论素材。</div><div class="chips"><span class="chip">★★★★★ 必看必背</span><span class="chip">★★★★☆ 高频考点</span><span class="chip">★★★☆☆ 建议了解</span></div><div id="affairsList"></div>`);renderAffairsPage()};
  window.renderAffairsPage=function(){let box=document.getElementById('affairsList');if(!box)return;box.innerHTML=affairs.length?[...affairs].sort((a,b)=>(b.date||'').localeCompare(a.date||'')||score(b)-score(a)).map(x=>affairCard(x,true)).join(''):'<div class="muted">暂时还没有时政条目。</div>'};
  window.openAffairSources=function(){let ss=sources();show(`<h3>⚙️ 时政来源管理</h3><div class="muted">官方来源用于事实核验。你也可以添加小红书等备考整理来源，作为选题参考。</div><div id="sourceList">${ss.map((s,i)=>`<div class="task"><input type="checkbox" ${s.enabled?'checked':''} onchange="toggleAffairSource(${i},this.checked)"><div class="txt"><b>${esc(s.name)}</b><div class="muted">${esc(s.type)}</div></div><button class="mini" onclick="removeAffairSource(${i})">×</button></div>`).join('')}</div><input id="newSourceName" placeholder="例如：小红书 · 某某公考老师"><select id="newSourceType"><option>备考整理</option><option>官方</option><option>媒体</option></select><button class="btn" onclick="addAffairSource()">＋ 添加来源</button>`)};
  window.toggleAffairSource=function(i,v){let ss=sources();if(ss[i])ss[i].enabled=v;localStorage.setItem(sourceKey,JSON.stringify(ss))};window.removeAffairSource=function(i){let ss=sources();ss.splice(i,1);localStorage.setItem(sourceKey,JSON.stringify(ss));openAffairSources()};window.addAffairSource=function(){let n=document.getElementById('newSourceName').value.trim();if(!n)return;let ss=sources();ss.push({name:n,type:document.getElementById('newSourceType').value,enabled:true});localStorage.setItem(sourceKey,JSON.stringify(ss));openAffairSources()};
  fetch('./data/current-affairs.json?ts='+Date.now()).then(r=>r.ok?r.json():Promise.reject()).then(j=>{affairs=Array.isArray(j.items)?j.items:[];render()}).catch(()=>{});
})();