/* 晓的工作台：每日时政前端模块 v2，申论素材联动 */
(function(){
  let affairs=[],dailyPicks={};const favKey='xiao_affairs_favorites',sourceKey='xiao_affairs_sources',civilKey='xiao_civil_service_v1';
  const defaults=[{name:'中国政府网',type:'官方',enabled:true},{name:'新华社/新华网',type:'官方',enabled:true},{name:'国务院部门',type:'官方',enabled:true},{name:'人民日报',type:'官方',enabled:true}];
  function favorites(){try{return JSON.parse(localStorage.getItem(favKey)||'[]')}catch{return []}}function sources(){try{return JSON.parse(localStorage.getItem(sourceKey)||'null')||defaults}catch{return defaults}}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function score(x){return Math.max(1,Math.min(5,+x.score||3))}function stars(x){let n=score(x);return '★'.repeat(n)+'☆'.repeat(5-n)}function civil(){try{let c=JSON.parse(localStorage.getItem(civilKey))||{};c.materials=c.materials||[];return c}catch{return{materials:[]}}}function savedMaterial(id){return civil().materials.some(x=>x.affairId===id)}
  function affairCard(x,full=false){let fav=favorites().includes(x.id),also=(x.also_sources||[]),saved=savedMaterial(x.id);return `<div class="node"><div class="head"><div class="txt">${esc(x.title)}</div><button class="mini" onclick="toggleAffairFav('${esc(x.id)}')">${fav?'★':'☆'}</button></div><div class="muted" style="margin:5px 0">${esc(x.date||'')} · ${esc(x.category||'时政')} · ${esc(x.source||'权威来源')}${also.length?' · '+(also.length+1)+' 个权威来源':''}</div><div style="margin:5px 0"><b>${stars(x)}</b> <span class="muted">考试价值 ${score(x)}/5</span></div><div style="line-height:1.65">${esc(x.summary||'')}</div>${full?`<div class="chips"><span class="chip">行测常识</span><span class="chip">申论素材</span></div>${x.exam_point?`<div style="margin-top:10px"><b>考点：</b>${esc(x.exam_point)}</div>`:''}${x.essay_material?`<div style="margin-top:8px"><b>申论积累：</b>${esc(x.essay_material)}</div>`:''}<button class="mini" style="width:100%;margin-top:10px" onclick="saveAffairToShenlun('${esc(x.id)}')">${saved?'✓ 已存入申论素材库':'＋ 存入申论素材库'}</button>${x.url?`<div style="margin-top:10px"><a href="${esc(x.url)}" target="_blank" rel="noopener">查看权威原文</a></div>`:''}`:''}</div>`}
  function today(){return new Date().toLocaleDateString('sv-SE')}function picked(date){let ids=dailyPicks[date]||[];return ids.map(id=>affairs.find(x=>x.id===id)).filter(Boolean)}
  window.saveAffairToShenlun=function(id){let x=affairs.find(a=>a.id===id);if(!x)return;let c=civil();if(c.materials.some(m=>m.affairId===id)){if(typeof accountPanel==='function')accountPanel('这条时政已经在申论素材库里了');return}let text=x.essay_material||x.summary||x.exam_point||x.title;c.materials.unshift({id:Date.now(),affairId:id,topic:x.category||'时政积累',title:x.title,text,source:x.source||'每日时政',url:x.url||'',date:x.date||today(),score:score(x)});localStorage.setItem(civilKey,JSON.stringify(c));if(typeof queueCloud==='function')queueCloud();renderAffairsPage()};
  window.toggleAffairFav=function(id){let f=favorites(),i=f.indexOf(id);i>=0?f.splice(i,1):f.push(id);localStorage.setItem(favKey,JSON.stringify(f));render();renderAffairsPage()};
  window.currentCard=function(){let d=today(),items=picked(d);if(!items.length)items=affairs.filter(x=>x.date===d).sort((a,b)=>score(b)-score(a)).slice(0,5);if(!items.length)items=[...affairs].sort((a,b)=>(b.date||'').localeCompare(a.date||'')||score(b)-score(a)).slice(0,5);return `<div class="card"><h3>📰 公务员 · 今日必看</h3><div class="muted" style="margin-bottom:8px">每天精选最多 5 条，优先高价值且覆盖不同主题。</div>${items.length?items.map(x=>affairCard(x,false)).join(''):'<div class="muted">今日时政数据正在准备中。</div>'}<div class="row"><button class="mini" onclick="openAffairs('today')">今日精选</button><button class="mini" onclick="openAffairs('all')">全部时政</button><button class="mini" onclick="openAffairSources()">来源管理</button></div></div>`};
  window.openAffairs=function(mode='today'){let d=today();show(`<h3>📰 每日时政</h3><div class="muted">每日精选用于快速复习，全部时政用于查漏补缺和素材积累。</div><div class="chips"><span class="chip ${mode==='today'?'active':''}" onclick="setAffairMode('today')">今日精选</span><span class="chip ${mode==='all'?'active':''}" onclick="setAffairMode('all')">全部</span><span class="chip ${mode==='fav'?'active':''}" onclick="setAffairMode('fav')">收藏</span></div><div id="affairsList" data-mode="${mode}"></div>`);renderAffairsPage()};window.setAffairMode=function(mode){openAffairs(mode)};
  window.renderAffairsPage=function(){let box=document.getElementById('affairsList');if(!box)return;let mode=box.dataset.mode||'today',list=[];if(mode==='today'){list=picked(today());if(!list.length)list=affairs.filter(x=>x.date===today()).sort((a,b)=>score(b)-score(a)).slice(0,5)}else if(mode==='fav'){let f=favorites();list=affairs.filter(x=>f.includes(x.id))}else list=[...affairs].sort((a,b)=>(b.date||'').localeCompare(a.date||'')||score(b)-score(a));box.innerHTML=list.length?list.map(x=>affairCard(x,true)).join(''):'<div class="muted">这里暂时没有内容。</div>'};
  window.openAffairSources=function(){let ss=sources();show(`<h3>⚙️ 时政来源管理</h3><div class="muted">官方来源用于事实核验。小红书等备考整理来源可以作为选题参考。</div><div>${ss.map((s,i)=>`<div class="task"><input type="checkbox" ${s.enabled?'checked':''} onchange="toggleAffairSource(${i},this.checked)"><div class="txt"><b>${esc(s.name)}</b><div class="muted">${esc(s.type)}</div></div><button class="mini" onclick="removeAffairSource(${i})">×</button></div>`).join('')}</div><input id="newSourceName" placeholder="例如：小红书 · 某某公考老师"><select id="newSourceType"><option>备考整理</option><option>官方</option><option>媒体</option></select><button class="btn" onclick="addAffairSource()">＋ 添加来源</button>`)};
  window.toggleAffairSource=function(i,v){let ss=sources();if(ss[i])ss[i].enabled=v;localStorage.setItem(sourceKey,JSON.stringify(ss))};window.removeAffairSource=function(i){let ss=sources();ss.splice(i,1);localStorage.setItem(sourceKey,JSON.stringify(ss));openAffairSources()};window.addAffairSource=function(){let n=document.getElementById('newSourceName').value.trim();if(!n)return;let ss=sources();ss.push({name:n,type:document.getElementById('newSourceType').value,enabled:true});localStorage.setItem(sourceKey,JSON.stringify(ss));openAffairSources()};
  fetch('./data/current-affairs.json?ts='+Date.now()).then(r=>r.ok?r.json():Promise.reject()).then(j=>{affairs=Array.isArray(j.items)?j.items:[];dailyPicks=j.daily_picks||{};render()}).catch(()=>{});
})();