/* 晓的工作台：数据备份与恢复 v1 */
(function(){
const KEYS=['xiao_workbench_v4','xiao_study_hubs_v2','xiao_psychology_hub_v1','xiao_weekly_reflections','xiao_current_affairs_v1'];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function snapshot(){let stores={};KEYS.forEach(k=>{let v=localStorage.getItem(k);if(v!==null)stores[k]=v});return{app:'晓的工作台',version:1,createdAt:new Date().toISOString(),stores}}
function download(name,text){let blob=new Blob([text],{type:'application/json;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
window.exportWorkbenchData=function(){let d=new Date().toISOString().slice(0,10);download(`晓的工作台备份-${d}.json`,JSON.stringify(snapshot(),null,2))};
window.importWorkbenchData=function(){let input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{let f=input.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let pack=JSON.parse(r.result);if(pack?.app!=='晓的工作台'||!pack.stores)throw new Error('invalid');let count=0;Object.entries(pack.stores).forEach(([k,v])=>{if(KEYS.includes(k)&&typeof v==='string'){JSON.parse(v);localStorage.setItem(k,v);count++}});alert(`已恢复 ${count} 组数据，页面将刷新。`);location.reload()}catch(e){alert('备份文件无法识别，请选择由晓的工作台导出的 JSON 备份。')}};r.readAsText(f,'utf-8')};input.click()};
window.openDataManager=function(){let s=snapshot(),size=Object.values(s.stores).reduce((n,v)=>n+new Blob([v]).size,0),kb=(size/1024).toFixed(1);show(`<h3>💾 数据管理</h3><div class="muted">当前学习记录主要保存在浏览器本地。建议在重要更新前手动导出一次完整备份。</div><div class="node"><b>当前数据</b><div class="muted" style="margin:6px 0 0">${Object.keys(s.stores).length} 组数据 · 约 ${kb} KB</div></div><button class="btn" style="width:100%" onclick="exportWorkbenchData()">导出完整备份</button><button class="mini" style="width:100%;margin-top:8px" onclick="importWorkbenchData()">从备份恢复</button><div class="node" style="margin-top:12px"><b>备份包含</b><div style="line-height:1.8;margin-top:6px">今日任务与计划<br>教师编知识点、刷题与错题记录<br>心理学书籍、论文、概念、知识网络与复习状态<br>周复盘和已保存的时政数据</div></div><div class="muted">恢复会覆盖这些模块当前的本地记录。导入前可以先导出一份现有数据。</div>`)};
setTimeout(()=>{let more=document.getElementById('otherModules');if(more&&!document.getElementById('dataManagerEntry')){let b=document.createElement('button');b.id='dataManagerEntry';b.className='mini';b.style.width='100%';b.style.margin='8px 0';b.textContent='💾 数据备份与恢复';b.onclick=openDataManager;more.parentNode.insertBefore(b,more.nextSibling)}},450);
})();