/* 晓的工作台：计划系统增强层 */
(function(){
function iso(d=new Date()){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}function kidsP(id){return data.plans.filter(p=>p.parent===id)}function linked(id){return data.tasks.find(t=>t.planId===id)}function area(p){let x=p;while(x&&!x.area&&x.parent!=null)x=data.plans.find(q=>q.id===x.parent);return x?.area||'teacher'}
window.planProgress=function(id){let leaves=descendants(id).map(x=>data.plans.find(p=>p.id===x)).filter(p=>p?.level==='task');if(leaves.length)return Math.round(leaves.filter(p=>linked(p.id)?.done).length/leaves.length*100);let ids=descendants(id),ts=data.tasks.filter(t=>t.planId&&ids.includes(t.planId));return ts.length?Math.round(ts.filter(t=>t.done).length/ts.length*100):0};
window.todayPlanCard=function(){let today=iso(),days=data.plans.filter(p=>p.level==='day'&&p.date===today);if(!days.length)days=data.plans.filter(p=>p.level==='day'&&!p.date).slice(0,1);if(!days.length)return `<div class="card"><h3>🎯 今日关联计划</h3><div class="muted">今天还没有关联计划。到“计划”中建立日计划并选择今天。</div></div>`;return `<div class="card"><h3>🎯 今日关联计划</h3>${days.map(p=>`<div class="node"><div class="head"><div class="txt">${e(p.title)}</div><span class="tag">${planProgress(p.id)}%</span></div><div class="muted" style="margin:4px 0 0">${e(p.date||today)}</div><div class="progress"><div class="fill" style="width:${planProgress(p.id)}%"></div></div>${kidsP(p.id).map(k=>{let t=linked(k.id);return `<div class="task ${t?.done?'done':''}"><div class="txt">${e(k.title)}</div>${t?`<span class="tag">${t.done?'已完成':'已加入'}</span>`:`<button class="mini" onclick="makeTask(${k.id})">加入今日</button>`}</div>`}).join('')}</div>`).join('')}</div>`};
window.planForm=function(parent,level){let labels={month:'月计划',week:'周计划',day:'日计划',task:'知识点'},extra='';if(level==='month')extra=`<label class="muted">所属方向</label><select id="pa"><option value="civil">公务员</option><option value="teacher" selected>教师编</option><option value="psy">心理学</option></select><label class="muted">月份</label><input id="pm" type="month" value="${iso().slice(0,7)}">`;if(level==='week')extra=`<label class="muted">本周开始日期</label><input id="pd" type="date" value="${iso()}">`;if(level==='day')extra=`<label class="muted">具体日期</label><input id="pd" type="date" value="${iso()}">`;show(`<h3>新建${labels[level]}</h3><input id="pt" placeholder="输入${labels[level]}内容">${extra}<div class="row"><button class="mini" onclick="closeM()">取消</button><button class="btn" onclick="savePlan(${parent===null?'null':parent},'${level}')">保存</button></div>`)};
window.savePlan=function(parent,level){if(!pt.value.trim())return;let par=parent==null?null:data.plans.find(x=>x.id===parent),item={id:Date.now(),parent,level,title:pt.value.trim()};if(level==='month'){item.area=pa.value;item.month=pm.value||iso().slice(0,7)}else{item.area=par?area(par):null;item.month=par?.month||null;if(level==='week'||level==='day')item.date=pd.value||iso()}data.plans.push(item);save();closeM()};
window.editPlan=function(id){let p=data.plans.find(x=>x.id===id),extra='';if(!p)return;if(p.level==='month')extra=`<label class="muted">月份</label><input id="epm" type="month" value="${e(p.month||iso().slice(0,7))}">`;if(p.level==='week'||p.level==='day')extra=`<label class="muted">日期</label><input id="epd" type="date" value="${e(p.date||iso())}">`;show(`<h3>修改计划</h3><input id="ept" value="${e(p.title)}">${extra}<div class="row"><button class="mini" onclick="closeM()">取消</button><button class="btn" onclick="savePlanEdit(${id})">保存</button></div>`)};window.savePlanEdit=function(id){let p=data.plans.find(x=>x.id===id);if(!p||!ept.value.trim())return;p.title=ept.value.trim();if(p.level==='month')p.month=epm.value;if(p.level==='week'||p.level==='day')p.date=epd.value;save();closeM()};
window.makeTask=function(id){let p=data.plans.find(x=>x.id===id);if(!p)return;if(data.tasks.some(t=>t.planId===id)){alert('这个知识点已经加入今日任务');return}taskForm(area(p),id);setTimeout(()=>tt.value=p.title,0)};
window.planHTML=function(p){let cs=kidsP(p.id),labels={month:'月',week:'周',day:'日',task:'知识点'},next={month:'week',week:'day',day:'task'},q=planProgress(p.id),meta=[];if(p.month)meta.push(p.month);if(p.date)meta.push(p.date);let t=p.level==='task'?linked(p.id):null;return `<div class="tree"><div class="node"><div class="head"><div class="txt"><span class="tag">${labels[p.level]}</span> ${e(p.title)}</div><span class="tag">${q}%</span><div class="actions"><button class="mini" onclick="editPlan(${p.id})">✎</button><button class="mini" onclick="delPlan(${p.id})">×</button></div></div>${meta.length?`<div class="muted" style="margin:5px 0 0">${e(meta.join(' · '))}</div>`:''}<div class="progress"><div class="fill" style="width:${q}%"></div></div>${p.level==='task'?(t?`<div class="muted" style="margin:8px 0 0">${t.done?'已完成':'已加入今日任务'}</div>`:`<button class="mini" style="margin-top:8px" onclick="makeTask(${p.id})">＋ 加入今日任务</button>`):`<button class="mini" style="margin-top:8px" onclick="planForm(${p.id},'${next[p.level]}')">＋ 继续拆分</button>`}</div>${cs.map(planHTML).join('')}</div>`};window.renderPlans=function(){let ms=data.plans.filter(p=>p.level==='month').sort((a,b)=>(b.month||'').localeCompare(a.month||''));planTree.innerHTML=ms.length?ms.map(planHTML).join(''):'<div class="card muted">还没有月计划。</div>'};render();
})();