/* 晓的工作台：心理学专业成长中心 v1 */
(function(){
const KEY='xiao_psychology_hub_v1';const AREAS=[['general','普通心理学'],['development','发展心理学'],['social','社会心理学'],['cognitive','认知心理学'],['personality','人格心理学'],['stats','心理统计与测量'],['research','研究方法']];
let psy=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||{books:[],concepts:[],papers:[],notes:[],experiments:[]}}catch{return{books:[],concepts:[],papers:[],notes:[],experiments:[]}}})();function saveP(){localStorage.setItem(KEY,JSON.stringify(psy))}function e2(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function area(id){return AREAS.find(x=>x[0]===id)?.[1]||'心理学'}function countDone(a){return a.length?`${a.filter(x=>x.done).length}/${a.length}`:'0'}
window.openPsychologyPro=function(){show(`<h3>🧠 心理学 · 专业成长</h3><div class="muted">用阅读、概念、经典研究、论文和笔记逐渐建立自己的专业知识库。</div><div class="summary"><div class="card"><div class="num">${countDone(psy.books)}</div><small>书籍</small></div><div class="card"><div class="num">${countDone(psy.papers)}</div><small>论文</small></div><div class="card"><div class="num">${psy.concepts.length}</div><small>概念卡</small></div></div><div style="height:10px"></div>${[['books','📚 教材与书籍','阅读进度与读书笔记'],['concepts','🗂️ 核心概念卡','定义、理论、易混点'],['experiments','🧪 经典研究','经典实验与研究范式'],['papers','📄 论文阅读','问题、方法、结果、启发'],['notes','✍️ 专业笔记','自己的理解与知识连接']].map(x=>`<button class="module" onclick="openPsyShelf('${x[0]}')"><strong>${x[1]}</strong><div class="muted" style="margin:4px 0 0">${x[2]}</div></button>`).join('')}`)};
window.openPsyShelf=function(type){let titles={books:'教材与书籍',concepts:'核心概念卡',experiments:'经典研究',papers:'论文阅读',notes:'专业笔记'},arr=psy[type];show(`<h3>${titles[type]}</h3><div class="muted">按专业方向积累，并可以随时加入今日学习。</div>${arr.length?arr.slice().reverse().map((x,i)=>`<div class="node"><div class="head"><div class="txt">${e2(x.title)}</div>${type==='books'||type==='papers'?`<span class="tag">${x.done?'已完成':'进行中'}</span>`:''}</div><div class="muted" style="margin:4px 0">${e2(area(x.area))}${x.author?' · '+e2(x.author):''}</div>${x.content?`<div style="line-height:1.6">${e2(x.content)}</div>`:''}<div class="row" style="margin-top:8px"><button class="mini" onclick="psyItemToday('${type}',${arr.length-1-i})">加入今日</button><button class="mini" onclick="editPsyItem('${type}',${arr.length-1-i})">编辑</button></div></div>`).join(''):'<div class="muted">这里还没有内容，可以从第一条开始积累。</div>'}<button class="btn" style="width:100%" onclick="newPsyItem('${type}')">＋ 添加</button><button class="mini" style="width:100%;margin-top:8px" onclick="openPsychologyPro()">返回专业成长</button>`)};
function opts(v){return AREAS.map(x=>`<option value="${x[0]}" ${v===x[0]?'selected':''}>${x[1]}</option>`).join('')}
window.newPsyItem=function(type){editPsyItem(type,-1)};window.editPsyItem=function(type,i){let x=i>=0?psy[type][i]:{area:'general',title:'',author:'',content:'',done:false};let hint={books:'例如：普通心理学教材 / 认知心理学导论',concepts:'例如：工作记忆 / 自我效能感',experiments:'例如：斯特鲁普效应',papers:'输入论文标题',notes:'输入笔记主题'}[type];show(`<h3>${i>=0?'编辑':'添加'}心理学资料</h3><select id="ppArea">${opts(x.area)}</select><input id="ppTitle" value="${e2(x.title)}" placeholder="${hint}"><input id="ppAuthor" value="${e2(x.author||'')}" placeholder="作者 / 学者，可留空"><textarea id="ppContent" style="width:100%;min-height:130px;padding:11px;border:1px solid var(--line);border-radius:10px" placeholder="记录定义、研究问题、方法、结论、自己的理解或易混点">${e2(x.content||'')}</textarea>${type==='books'||type==='papers'?`<label><input id="ppDone" type="checkbox" ${x.done?'checked':''}> 已完成</label>`:''}<button class="btn" style="width:100%;margin-top:10px" onclick="savePsyItem('${type}',${i})">保存</button>`)};
window.savePsyItem=function(type,i){let x={area:ppArea.value,title:ppTitle.value.trim(),author:ppAuthor.value.trim(),content:ppContent.value.trim(),done:typeof ppDone!=='undefined'?ppDone.checked:false,updated:new Date().toISOString()};if(!x.title)return;if(i>=0)psy[type][i]=x;else psy[type].push(x);saveP();openPsyShelf(type)};
window.psyItemToday=function(type,i){let x=psy[type][i];if(!x)return;let label={books:'阅读',concepts:'复习概念',experiments:'经典研究',papers:'论文阅读',notes:'整理笔记'}[type];data.tasks.push({id:Date.now(),area:'psy',text:`心理学 · ${label}：${x.title}`,done:false,psyRef:`${type}|${i}`});save();closeM()};
const oldPsy=window.openPsyHub;window.openPsyHub=function(){openPsychologyPro()};
})();