/* 晓的工作台：心理学智能复习系统 v1 */
(function(){
const KEY='xiao_psychology_hub_v1';function get(){try{return JSON.parse(localStorage.getItem(KEY))||{books:[],concepts:[],papers:[],notes:[],experiments:[]}}catch{return{books:[],concepts:[],papers:[],notes:[],experiments:[]}}}function put(x){localStorage.setItem(KEY,JSON.stringify(x))}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function days(a,b){return Math.floor((new Date(a)-new Date(b))/86400000)}function today(){return new Date().toISOString().slice(0,10)}function label(t){return{concepts:'概念卡',experiments:'经典研究',papers:'论文',notes:'专业笔记',books:'书籍'}[t]||t}
function queue(){let d=get(),now=today(),out=[];['concepts','experiments','papers'].forEach(t=>(d[t]||[]).forEach((x,i)=>{let r=x.review||{},last=r.last||x.updated?.slice(0,10)||x.date||now,level=+r.level||0,interval=[0,1,3,7,14,30,60][Math.min(level,6)],due=days(now,last)>=interval,priority=(due?10:0)+(x.links||[]).length+(t==='concepts'?2:0)+(t==='papers'&&x.reading?.deep?2:0);if(due)out.push({t,i,x,priority,last,level})}));return out.sort((a,b)=>b.priority-a.priority)}
window.openPsyReview=function(){let q=queue();show(`<h3>🧠 心理学 · 今日复习</h3><div class="muted">按 1、3、7、14、30、60 天逐步拉开复习间隔。连接较多的核心知识会优先出现。</div>${q.length?q.slice(0,20).map(a=>`<div class="task"><div class="txt"><b>${esc(a.x.title)}</b><div class="muted">${label(a.t)} · 第 ${a.level+1} 次复习${(a.x.links||[]).length?` · ${(a.x.links||[]).length} 个知识连接`:''}</div></div><button class="mini" onclick="reviewPsyItem('${a.t}',${a.i},'hard')">模糊</button><button class="mini" onclick="reviewPsyItem('${a.t}',${a.i},'good')">掌握</button></div>`).join(''):'<div class="muted">今天暂时没有到期内容。继续积累概念、经典研究和论文即可。</div>'}<button class="mini" style="width:100%;margin-top:10px" onclick="psyReviewToToday()">把今日复习加入任务</button>`)};
window.reviewPsyItem=function(t,i,result){let d=get(),x=d[t]?.[i];if(!x)return;x.review=x.review||{};x.review.last=today();x.review.level=result==='good'?Math.min((+x.review.level||0)+1,6):0;x.review.count=(+x.review.count||0)+1;x.review.lastResult=result;put(d);openPsyReview()};
window.psyReviewToToday=function(){let q=queue().slice(0,5);q.forEach(a=>{let ref=`${a.t}|${a.i}`;if(!data.tasks.some(t=>t.psyReviewRef===ref&&!t.done))data.tasks.push({id:Date.now()+a.i,area:'psy',text:`心理学复习 · ${a.x.title}`,done:false,psyReviewRef:ref})});save();closeM()};
window.psyReviewCard=function(){let q=queue();return `<div class="card"><h3>🧠 心理学复习</h3><div class="muted">${q.length?`今天有 ${q.length} 项知识到期，优先复习前 ${Math.min(5,q.length)} 项。`:'今天没有到期的专业知识。'}</div>${q.slice(0,3).map(a=>`<div class="task"><div class="txt"><b>${esc(a.x.title)}</b><div class="muted">${label(a.t)}</div></div></div>`).join('')}<button class="mini" style="width:100%;margin-top:8px" onclick="openPsyReview()">进入复习</button></div>`};
const oldHome=window.openPsychologyPro;window.openPsychologyPro=function(){oldHome();let m=document.getElementById('modal');if(m&&!document.getElementById('psyReviewBtn'))m.insertAdjacentHTML('beforeend','<button id="psyReviewBtn" class="mini" style="width:100%;margin-top:8px" onclick="openPsyReview()">🧠 今日智能复习</button>')};
})();