/* 晓的工作台：多端界面与视觉系统 v1 */
(function(){
const KEY='xiao_ui_device_v1';
const css=`
:root{--ui-max:1180px;--ui-gap:16px;--ui-radius:18px;--ui-shadow:0 10px 35px rgba(31,41,55,.07)}
*{box-sizing:border-box}body{background:linear-gradient(180deg,color-mix(in srgb,var(--a) 5%,var(--bg)) 0,var(--bg) 240px);letter-spacing:.01em}.card,.node,.task{transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.card{border-radius:var(--ui-radius)!important;box-shadow:var(--ui-shadow);border:1px solid color-mix(in srgb,var(--line) 78%,transparent)!important}.node{border-radius:14px!important}.btn,.mini,input,select,textarea{border-radius:12px!important}.btn{box-shadow:0 5px 14px color-mix(in srgb,var(--a) 18%,transparent)}.progress{height:8px!important;border-radius:999px;overflow:hidden}.fill{border-radius:999px}.tag{border-radius:999px!important}.bottom{backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);background:color-mix(in srgb,var(--card) 88%,transparent)!important}.nav{transition:.18s ease}.nav.on{background:color-mix(in srgb,var(--a) 10%,transparent);border-radius:14px}.summary{gap:10px!important}.summary .card{box-shadow:none!important;background:color-mix(in srgb,var(--a) 5%,var(--card))}
body[data-device="mobile"]{--ui-max:520px;--ui-gap:12px;--ui-radius:16px}.device-shell{max-width:var(--ui-max);margin:auto}body[data-device="mobile"] #dashboard,body[data-device="mobile"] #planPage,body[data-device="mobile"] main{max-width:520px;margin-left:auto;margin-right:auto}body[data-device="mobile"] .summary{grid-template-columns:repeat(3,1fr)}body[data-device="mobile"] .card{padding:14px!important}body[data-device="mobile"] .bottom{max-width:520px;left:50%!important;transform:translateX(-50%);border-radius:18px 18px 0 0}
body[data-device="tablet"]{--ui-max:920px;--ui-gap:18px;--ui-radius:20px}body[data-device="tablet"] #dashboard,body[data-device="tablet"] #planPage,body[data-device="tablet"] main{max-width:920px;margin-left:auto;margin-right:auto;padding-left:22px!important;padding-right:22px!important}body[data-device="tablet"] .summary{grid-template-columns:repeat(3,1fr)}body[data-device="tablet"] .bottom{max-width:720px;left:50%!important;transform:translateX(-50%);bottom:14px!important;border:1px solid var(--line);border-radius:22px!important;box-shadow:0 12px 38px rgba(0,0,0,.12)}body[data-device="tablet"] .mbg .modal,body[data-device="tablet"] #modal{max-width:720px!important;margin:auto}
body[data-device="desktop"]{--ui-max:1280px;--ui-gap:22px;--ui-radius:20px}body[data-device="desktop"] #dashboard,body[data-device="desktop"] #planPage,body[data-device="desktop"] main{max-width:1180px;margin-left:auto;margin-right:auto;padding-left:28px!important;padding-right:28px!important}body[data-device="desktop"] #dashboard{display:grid;grid-template-columns:repeat(12,1fr);gap:16px;align-items:start}body[data-device="desktop"] #dashboard>*{grid-column:span 6;margin:0!important}body[data-device="desktop"] #dashboard>#learningCommandBtn,body[data-device="desktop"] #dashboard>#workbenchOverviewBtn{grid-column:span 12}body[data-device="desktop"] .summary{grid-template-columns:repeat(3,1fr)}body[data-device="desktop"] .bottom{width:88px!important;height:auto!important;top:50%;bottom:auto!important;left:18px!important;right:auto!important;transform:translateY(-50%);flex-direction:column;padding:10px 8px!important;border:1px solid var(--line);border-radius:22px!important;box-shadow:0 12px 38px rgba(0,0,0,.1)}body[data-device="desktop"] .nav{width:70px;min-height:62px}body[data-device="desktop"] .mbg{align-items:center!important}body[data-device="desktop"] #modal{max-width:760px!important;border-radius:24px!important;margin:auto!important;max-height:84vh!important}body[data-device="desktop"] .task:hover,body[data-device="desktop"] .node:hover{border-color:color-mix(in srgb,var(--a) 35%,var(--line))}
@media(max-width:620px){body[data-device="mobile"] .row{gap:7px}body[data-device="mobile"] .summary .num{font-size:20px!important}body[data-device="mobile"] h3{font-size:17px}}
`;
let st=document.createElement('style');st.id='responsiveUiStyle';st.textContent=css;document.head.appendChild(st);
function auto(){let w=innerWidth;return w<700?'mobile':w<1050?'tablet':'desktop'}function current(){return localStorage.getItem(KEY)||'auto'}function apply(v=current()){let d=v==='auto'?auto():v;document.body.dataset.device=d;document.documentElement.dataset.deviceMode=v;localStorage.setItem(KEY,v);return d}window.setWorkbenchDevice=function(v){apply(v);closeM();setTimeout(()=>window.openWorkbenchSettings(),60)};
window.openWorkbenchSettings=function(){let v=current(),actual=document.body.dataset.device||apply(v);show(`<h3>⚙️ 界面设置</h3><div class="muted">可以跟随当前屏幕，也可以固定使用某一种布局。选择会保存在这台设备。</div><div class="node"><b>设备界面</b><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:10px">${[['auto','自动适配','根据屏幕宽度切换'],['mobile','手机端','单列、底部导航'],['tablet','平板端','宽内容区、悬浮导航'],['desktop','电脑端','双栏工作区、侧边导航']].map(x=>`<button class="${v===x[0]?'btn':'mini'}" style="padding:12px;text-align:left" onclick="setWorkbenchDevice('${x[0]}')"><b>${x[1]}</b><div style="font-size:11px;opacity:.7;margin-top:3px">${x[2]}</div></button>`).join('')}</div><div class="muted" style="margin-top:9px">当前实际布局：${{mobile:'手机端',tablet:'平板端',desktop:'电脑端'}[actual]}</div></div><div class="node"><b>界面设计</b><div class="muted" style="margin-top:6px">统一卡片圆角、留白、阴影、按钮层级、进度条和导航样式。电脑端会利用横向空间，平板端强调触控和阅读，手机端保持单手操作。</div></div><button class="mini" style="width:100%" onclick="openWorkbenchOverview()">工作台状态与数据</button>`)};
function settingsEntry(){let d=document.getElementById('dashboard');if(!d||document.getElementById('uiSettingsBtn'))return;let b=document.createElement('button');b.id='uiSettingsBtn';b.className='mini';b.textContent='⚙️ 界面设置';b.onclick=openWorkbenchSettings;let anchor=document.getElementById('workbenchOverviewBtn');if(anchor)anchor.insertAdjacentElement('afterend',b);else d.prepend(b)}
apply();addEventListener('resize',()=>{if(current()==='auto')apply('auto')});const old=window.renderDashboard;window.renderDashboard=function(){let r=old&&old.apply(this,arguments);setTimeout(settingsEntry,0);return r};setTimeout(settingsEntry,500);
})();