/* 晓的工作台：教师编 + 心理学学习中心 v1 */
(function(){
const KEY='xiao_study_hubs_v1';
const DEF={teacher:{subjects:[{id:'edu',name:'教育学',progress:0},{id:'psyedu',name:'心理学',progress:0},{id:'law',name:'教育法律法规',progress:0},{id:'ethics',name:'教师职业道德',progress:0}],records:[]},psy:{subjects:[{id:'general',name:'普通心理学',progress:0},{id:'development',name:'发展心理学',progress:0},{id:'social',name:'社会心理学',progress:0},{id:'cognitive',name:'认知心理学',progress:0},{id:'personality',name:'人格心理学',progress:0},{id:'stats',name:'心理统计与测量',progress:0},{id:'research',name:'研究方法',progress:0}],records:[]}};
let hub=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||DEF}catch{return DEF}})();
function saveHub(){localStorage.setItem(KEY,JSON.stringify(hub));}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function avg(type){let a=hub[type].subjects;return a.length?Math.round(a.reduce((s,x)=>s+(+x.progress||0),0)/a.length):0}
function subjectRows(type){return hub[type].subjects.map((s,i)=>`<div class="node"><div class="head"><div class="txt">${esc(s.name)}</div><span class="tag">${s.progress||0}%</span></div><div class="progress"><div class="fill" style="width:${s.progress||0}%"></div></div><div class="row" style="margin-top:8px"><button class="mini" onclick="studyProgress('${type}',${i})">更新进度</button><button class="mini" onclick="studyToPlan('${type}',${i})">加入计划</button><button class="mini" onclick="studyRecord('${type}',${i})">学习记录</button></div></div>`).join('')}
function records(type){let r=hub[type].records.slice().reverse().slice(0,8);return r.length?r.map(x=>`<div class="task"><div class="txt"><b>${esc(x.subject)}</b> · ${esc(x.text)}<div class="muted" style="margin:2px 0 0">${esc(x.date)}</div></div></div>`).join(''):'<div class="muted">还没有学习记录。</div>'}
window.openTeacherHub=function(){show(`<h3>🏫 教师编 · 教综学习中心</h3><div class="muted">把教综拆成科目进度、章节学习、刷题与计划。总进度 ${avg('teacher')}%</div><div class="progress"><div class="fill" style="width:${avg('teacher')}%"></div></div><div class="chips"><span class="chip">知识框架</span><span class="chip">背诵</span><span class="chip">刷题</span><span class="chip">错题</span><span class="chip">教育时政</span></div><div style="margin-top:12px">${subjectRows('teacher')}</div><h3 style="margin-top:16px">最近学习记录</h3>${records('teacher')}`)};
window.openPsyHub=function(){show(`<h3>🧠 心理学 · 专业成长中心</h3><div class="muted">兼顾教师编需要的心理学知识和长期专业能力。总进度 ${avg('psy')}%</div><div class="progress"><div class="fill" style="width:${avg('psy')}%"></div></div><div class="chips"><span class="chip">教材体系</span><span class="chip">核心概念</span><span class="chip">经典研究</span><span class="chip">论文阅读</span><span class="chip">研究方法</span></div><div style="margin-top:12px">${subjectRows('psy')}</div><h3 style="margin-top:16px">最近学习记录</h3>${records('psy')}`)};
window.studyProgress=function(type,i){let s=hub[type].subjects[i];show(`<h3>更新进度 · ${esc(s.name)}</h3><input id="studyPct" type="number" min="0" max="100" value="${s.progress||0}" placeholder="0～100"><button class="btn" style="width:100%" onclick="saveStudyProgress('${type}',${i})">保存</button>`)};
window.saveStudyProgress=function(type,i){let v=Math.max(0,Math.min(100,+document.getElementById('studyPct').value||0));hub[type].subjects[i].progress=v;saveHub();type==='teacher'?openTeacherHub():openPsyHub()};
window.studyToPlan=function(type,i){let s=hub[type].subjects[i],area=type==='teacher'?'teacher':'psy';data.tasks.push({id:Date.now(),area,text:`${s.name}：今日学习`,done:false});save();closeM();if(typeof toast==='function')toast('已加入今日任务')};
window.studyRecord=function(type,i){let s=hub[type].subjects[i];show(`<h3>记录学习 · ${esc(s.name)}</h3><input id="studyNote" placeholder="例如：完成感觉与知觉，整理 12 个易错点"><button class="btn" style="width:100%" onclick="saveStudyRecord('${type}',${i})">保存记录</button>`)};
window.saveStudyRecord=function(type,i){let text=document.getElementById('studyNote').value.trim();if(!text)return;hub[type].records.push({subject:hub[type].subjects[i].name,text,date:new Date().toLocaleDateString('zh-CN')});saveHub();type==='teacher'?openTeacherHub():openPsyHub()};
const oldOpen=window.openModule;window.openModule=function(id){if(id==='teacher'){openTeacherHub();return}if(id==='psy'){openPsyHub();return}return oldOpen(id)};
})();