/* 晓的工作台：教师编 + 心理学学习中心 v2 */
(function(){
const KEY='xiao_study_hubs_v2',OLD='xiao_study_hubs_v1';
const DEF={teacher:{subjects:[
{id:'edu',name:'教育学',chapters:[['教育与教育学','教育概念','教育起源','教育发展'],['教育与社会发展','教育与生产力','教育与政治经济制度','教育与文化'],['教育与人的发展','个体身心发展规律','影响个体发展的因素'],['教育目的与制度','教育目的','我国教育目的','学校教育制度'],['课程','课程类型','课程理论','课程目标与实施'],['教学','教学原则','教学方法','教学过程规律'],['德育','德育原则','德育方法','德育过程规律']]},
{id:'psyedu',name:'心理学',chapters:[['心理学概述','心理现象','心理实质','研究方法'],['认知过程','感觉','知觉','注意','记忆','思维','想象'],['情绪情感与意志','情绪与情感','意志过程'],['个性心理','需要与动机','能力','气质','性格'],['学习心理','学习理论','学习动机','学习迁移','知识与技能学习'],['学生心理发展','认知发展','人格发展','社会性发展'],['心理健康与教师心理','心理健康教育','教师心理']]},
{id:'law',name:'教育法律法规',chapters:[['教育法基础','教育法律关系','教育法律责任'],['核心法律','教育法','义务教育法','教师法','未成年人保护法'],['学生与教师权利','学生权利保护','教师权利义务']]},
{id:'ethics',name:'教师职业道德',chapters:[['职业道德规范','爱国守法','爱岗敬业','关爱学生','教书育人','为人师表','终身学习'],['教师职业行为','师德评价','职业行为准则']]}
],records:[],knowledge:{}},psy:{subjects:[{id:'general',name:'普通心理学'},{id:'development',name:'发展心理学'},{id:'social',name:'社会心理学'},{id:'cognitive',name:'认知心理学'},{id:'personality',name:'人格心理学'},{id:'stats',name:'心理统计与测量'},{id:'research',name:'研究方法'}],records:[]}};
let hub=(()=>{try{let n=JSON.parse(localStorage.getItem(KEY)||'null');if(n)return n;let o=JSON.parse(localStorage.getItem(OLD)||'null');if(o){DEF.teacher.records=o.teacher?.records||[];DEF.psy.records=o.psy?.records||[];return DEF}return DEF}catch{return DEF}})();
function saveHub(){localStorage.setItem(KEY,JSON.stringify(hub))}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function kkey(s,c,k){return s+'|'+c+'|'+k}function kstate(s,c,k){return hub.teacher.knowledge[kkey(s,c,k)]||{learned:false,memorized:false,questions:0,wrong:0}}
function subjectPct(s){let all=[],si=hub.teacher.subjects.indexOf(s);(s.chapters||[]).forEach((c,ci)=>c.slice(1).forEach((k,ki)=>all.push(kstate(si,ci,ki))));return all.length?Math.round(all.filter(x=>x.learned).length/all.length*100):0}
function teacherAvg(){let a=hub.teacher.subjects;return a.length?Math.round(a.reduce((n,s)=>n+subjectPct(s),0)/a.length):0}
function psyPct(s){return +s.progress||0}function psyAvg(){let a=hub.psy.subjects;return a.length?Math.round(a.reduce((n,s)=>n+psyPct(s),0)/a.length):0}
function teacherRows(){return hub.teacher.subjects.map((s,i)=>`<div class="node"><div class="head"><div class="txt">${esc(s.name)}</div><span class="tag">${subjectPct(s)}%</span></div><div class="progress"><div class="fill" style="width:${subjectPct(s)}%"></div></div><button class="mini" style="width:100%;margin-top:8px" onclick="openTeacherSubject(${i})">进入章节与知识点</button></div>`).join('')}
function psyRows(){return hub.psy.subjects.map((s,i)=>`<div class="node"><div class="head"><div class="txt">${esc(s.name)}</div><span class="tag">${psyPct(s)}%</span></div><div class="progress"><div class="fill" style="width:${psyPct(s)}%"></div></div><div class="row" style="margin-top:8px"><button class="mini" onclick="studyProgress('psy',${i})">更新进度</button><button class="mini" onclick="studyToPlan('psy',${i})">加入今日</button><button class="mini" onclick="studyRecord('psy',${i})">记录</button></div></div>`).join('')}
function records(type){let r=hub[type].records.slice().reverse().slice(0,8);return r.length?r.map(x=>`<div class="task"><div class="txt"><b>${esc(x.subject)}</b> · ${esc(x.text)}<div class="muted" style="margin:2px 0 0">${esc(x.date)}</div></div></div>`).join(''):'<div class="muted">还没有学习记录。</div>'}
window.openTeacherHub=function(){show(`<h3>🏫 教师编 · 教综学习中心</h3><div class="muted">章节 → 知识点 → 学习 / 背诵 / 刷题 / 错题，并可加入今日任务。总进度 ${teacherAvg()}%</div><div class="progress"><div class="fill" style="width:${teacherAvg()}%"></div></div><div style="margin-top:12px">${teacherRows()}</div><h3 style="margin-top:16px">最近学习记录</h3>${records('teacher')}`)};
window.openTeacherSubject=function(si){let s=hub.teacher.subjects[si];show(`<h3>📚 ${esc(s.name)}</h3><div class="muted">点击章节展开知识点。每个知识点都能独立记录掌握情况。</div>${s.chapters.map((c,ci)=>{let ks=c.slice(1),done=ks.filter((k,ki)=>kstate(si,ci,ki).learned).length;return `<div class="node"><div class="head"><div class="txt">${esc(c[0])}</div><span class="tag">${done}/${ks.length}</span></div>${ks.map((k,ki)=>knowledgeRow(si,ci,ki,k)).join('')}</div>`}).join('')}<button class="mini" style="width:100%" onclick="openTeacherHub()">返回教综总览</button>`)};
function knowledgeRow(si,ci,ki,name){let x=kstate(si,ci,ki);return `<div class="task ${x.learned?'done':''}"><input type="checkbox" ${x.learned?'checked':''} onchange="toggleKnowledge(${si},${ci},${ki},this.checked)"><div class="txt">${esc(name)}<div class="muted" style="margin:3px 0 0">${x.memorized?'已背诵':'待背诵'} · 刷题 ${x.questions||0} · 错题 ${x.wrong||0}</div></div><button class="mini" onclick="knowledgePanel(${si},${ci},${ki})">管理</button></div>`}
window.toggleKnowledge=function(si,ci,ki,v){let x=kstate(si,ci,ki);x.learned=v;hub.teacher.knowledge[kkey(si,ci,ki)]=x;saveHub();openTeacherSubject(si)};
window.knowledgePanel=function(si,ci,ki){let s=hub.teacher.subjects[si],c=s.chapters[ci],name=c[ki+1],x=kstate(si,ci,ki);show(`<h3>${esc(name)}</h3><div class="muted">${esc(s.name)} · ${esc(c[0])}</div><label><input id="kpLearn" type="checkbox" ${x.learned?'checked':''}> 已学习</label><br><label><input id="kpMemo" type="checkbox" ${x.memorized?'checked':''}> 已完成背诵</label><input id="kpQ" type="number" min="0" value="${x.questions||0}" placeholder="累计刷题数"><input id="kpW" type="number" min="0" value="${x.wrong||0}" placeholder="累计错题数"><div class="row"><button class="btn" onclick="saveKnowledge(${si},${ci},${ki})">保存</button><button class="mini" onclick="knowledgeToToday(${si},${ci},${ki})">加入今日</button></div>`)};
window.saveKnowledge=function(si,ci,ki){hub.teacher.knowledge[kkey(si,ci,ki)]={learned:document.getElementById('kpLearn').checked,memorized:document.getElementById('kpMemo').checked,questions:+document.getElementById('kpQ').value||0,wrong:+document.getElementById('kpW').value||0};saveHub();openTeacherSubject(si)};
window.knowledgeToToday=function(si,ci,ki){let s=hub.teacher.subjects[si],c=s.chapters[ci],name=c[ki+1];data.tasks.push({id:Date.now(),area:'teacher',text:`教综 · ${s.name}：${name}`,done:false});save();closeM()};
window.openPsyHub=function(){show(`<h3>🧠 心理学 · 专业成长中心</h3><div class="muted">教材体系、核心概念、经典研究、论文阅读和研究方法。总进度 ${psyAvg()}%</div><div class="progress"><div class="fill" style="width:${psyAvg()}%"></div></div><div style="margin-top:12px">${psyRows()}</div><h3 style="margin-top:16px">最近学习记录</h3>${records('psy')}`)};
window.studyProgress=function(type,i){let s=hub[type].subjects[i];show(`<h3>更新进度 · ${esc(s.name)}</h3><input id="studyPct" type="number" min="0" max="100" value="${s.progress||0}"><button class="btn" style="width:100%" onclick="saveStudyProgress('${type}',${i})">保存</button>`)};
window.saveStudyProgress=function(type,i){hub[type].subjects[i].progress=Math.max(0,Math.min(100,+document.getElementById('studyPct').value||0));saveHub();openPsyHub()};
window.studyToPlan=function(type,i){let s=hub[type].subjects[i];data.tasks.push({id:Date.now(),area:type==='teacher'?'teacher':'psy',text:`${s.name}：今日学习`,done:false});save();closeM()};
window.studyRecord=function(type,i){let s=hub[type].subjects[i];show(`<h3>记录学习 · ${esc(s.name)}</h3><input id="studyNote" placeholder="今天学了什么、哪里还不熟"><button class="btn" style="width:100%" onclick="saveStudyRecord('${type}',${i})">保存记录</button>`)};
window.saveStudyRecord=function(type,i){let text=document.getElementById('studyNote').value.trim();if(!text)return;hub[type].records.push({subject:hub[type].subjects[i].name,text,date:new Date().toLocaleDateString('zh-CN')});saveHub();type==='teacher'?openTeacherHub():openPsyHub()};
const oldOpen=window.openModule;window.openModule=function(id){if(id==='teacher'){openTeacherHub();return}if(id==='psy'){openPsyHub();return}return oldOpen(id)};
})();