/* 晓的工作台：教综知识点与计划任务双向同步 v2 */
(function(){
const KEY='xiao_study_hubs_v2';function hub(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}function saveHub(h){localStorage.setItem(KEY,JSON.stringify(h))}function refState(ref){let h=hub();if(!h||!ref)return null;h.teacher.knowledge=h.teacher.knowledge||{};let x=h.teacher.knowledge[ref]||{learned:false,memorized:false,questions:0,wrong:0};return{h,x}}function planRef(id){return data.plans.find(p=>p.id===id)?.studyRef||null}
function syncTask(task){let ref=task?.studyRef||planRef(task?.planId),r=refState(ref);if(!r)return;r.x.learned=!!task.done;r.h.teacher.knowledge[ref]=r.x;saveHub(r.h)}window.syncTeacherStudyToTask=function(ref,learned){let p=data.plans.find(x=>x.studyRef===ref),t=p&&data.tasks.find(x=>x.planId===p.id);if(t){t.done=!!learned;localStorage.setItem('xiao_workbench_v4',JSON.stringify(data))}};
const oldToggle=window.toggle;window.toggle=function(id){if(typeof oldToggle==='function')oldToggle(id);syncTask(data.tasks.find(x=>x.id===id))};const oldMake=window.makeTask;window.makeTask=function(id){let p=data.plans.find(x=>x.id===id);if(typeof oldMake==='function')oldMake(id);if(!p?.studyRef)return;setTimeout(()=>{let t=data.tasks.find(x=>x.planId===id),r=refState(p.studyRef);if(t&&r){t.done=!!r.x.learned;localStorage.setItem('xiao_workbench_v4',JSON.stringify(data));render()}},0)};
window.teacherReviewQueue=function(){let h=hub();if(!h)return[];let out=[];Object.entries(h.teacher.knowledge||{}).forEach(([ref,x])=>{let [si,ci,ki]=ref.split('|').map(Number),s=h.teacher.subjects[si],c=s?.chapters?.[ci],name=c?.[ki+1];if(!name)return;let priority=(+x.wrong||0)*3+(x.learned&&!x.memorized?2:0);if(priority>0)out.push({ref,subject:s.name,chapter:c[0],name,wrong:+x.wrong||0,memorized:!!x.memorized,priority})});return out.sort((a,b)=>b.priority-a.priority)};
window.teacherReviewCard=function(){let q=teacherReviewQueue().slice(0,4);return `<div class="card"><h3>🔁 教综复习提醒</h3>${q.length?q.map(x=>`<div class="task"><div class="txt"><b>${x.name}</b><div class="muted" style="margin:2px 0 0">${x.subject} · ${x.wrong?`错题 ${x.wrong} 道`:'待背诵巩固'}</div></div></div>`).join(''):'<div class="muted">暂时没有待复习提醒。记录错题或待背诵知识点后会自动出现。</div>'}<button class="mini" style="width:100%;margin-top:8px" onclick="openTeacherReview()">查看复习队列</button></div>`};
window.openTeacherReview=function(){let q=teacherReviewQueue().slice(0,20);show(`<h3>🔁 教综复习队列</h3><div class="muted">错题越多优先级越高，其次安排已学习但还没背熟的知识点。</div>${q.length?q.map(x=>`<div class="task"><div class="txt"><b>${x.name}</b><div class="muted" style="margin:2px 0 0">${x.subject} · ${x.chapter} · ${x.wrong?`错题 ${x.wrong}`:'待背诵'}</div></div><button class="mini" onclick="reviewToToday('${x.ref}')">加入今日</button></div>`).join(''):'<div class="muted">目前没有需要优先复习的知识点。</div>'}`)};window.reviewToToday=function(ref){let x=teacherReviewQueue().find(q=>q.ref===ref);if(!x)return;if(!data.tasks.some(t=>t.studyRef===ref&&!t.done))data.tasks.push({id:Date.now(),area:'teacher',text:`教综复习 · ${x.subject}：${x.name}${x.wrong?`（错题 ${x.wrong}）`:''}`,done:false,studyRef:ref,review:true});save();closeM()};
const oldHub=window.openTeacherHub;window.openTeacherHub=function(){if(typeof oldHub==='function')oldHub();let m=document.getElementById('modal');if(m&&!document.getElementById('teacherReviewBtn'))m.insertAdjacentHTML('beforeend','<button id="teacherReviewBtn" class="mini" style="width:100%;margin-top:10px" onclick="openTeacherReview()">🔁 智能复习队列</button>')};const oldDash=window.renderDashboard;window.renderDashboard=function(){if(typeof oldDash==='function')oldDash();let d=document.getElementById('dashboard');if(d&&!document.getElementById('teacherReviewHome')){let w=document.createElement('div');w.id='teacherReviewHome';w.innerHTML=teacherReviewCard();d.appendChild(w)}};
})();