/* 晓的工作台：视觉精修 v1 */
(function(){
const css=`
body{font-feature-settings:"kern" 1,"liga" 1}.top,.header,header{border-bottom-color:color-mix(in srgb,var(--line) 65%,transparent)!important}.muted{line-height:1.55}.card>h3,.node>b{letter-spacing:-.01em}.task{border:1px solid color-mix(in srgb,var(--line) 72%,transparent)!important;background:color-mix(in srgb,var(--card) 96%,var(--bg));margin-top:8px!important}.task.done{opacity:.58}.mini{background:color-mix(in srgb,var(--card) 94%,var(--bg))!important;border-color:color-mix(in srgb,var(--line) 80%,transparent)!important}.btn{border:0!important}.num{letter-spacing:-.04em}.summary small{font-size:11px!important}.modal h3{letter-spacing:-.025em;margin-bottom:5px}.modal>.muted:first-of-type{margin-bottom:14px}.modal .node{padding:14px!important;border-color:color-mix(in srgb,var(--line) 72%,transparent)!important;background:color-mix(in srgb,var(--card) 97%,var(--bg))}.bottom .nav span{font-size:20px!important;margin-bottom:3px}.bottom .nav{font-size:11px!important;font-weight:650!important}.bottom .nav.on{color:var(--a)!important}
#uiSettingsBtn,#workbenchOverviewBtn{box-shadow:none!important;border-style:dashed!important}body[data-device="mobile"] #uiSettingsBtn,body[data-device="mobile"] #workbenchOverviewBtn{width:calc(50% - 5px)!important;display:inline-flex!important;justify-content:center;margin-right:6px!important}body[data-device="mobile"] #learningCommandBtn{min-height:48px;font-size:14px}body[data-device="mobile"] .modal{border-radius:24px 24px 0 0!important;padding:20px 16px calc(22px + env(safe-area-inset-bottom))!important}body[data-device="mobile"] .mbg{align-items:flex-end!important}
body[data-device="tablet"] #dashboard{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;align-items:start}body[data-device="tablet"] #dashboard>*{margin:0!important}body[data-device="tablet"] #learningCommandBtn,body[data-device="tablet"] #workbenchOverviewBtn,body[data-device="tablet"] #uiSettingsBtn{grid-column:span 2}body[data-device="tablet"] .card{padding:18px!important}body[data-device="tablet"] .task{padding:13px!important}
body[data-device="desktop"]{padding-left:108px}body[data-device="desktop"] #dashboard{padding-top:20px!important;padding-bottom:42px!important}body[data-device="desktop"] #dashboard>.card{min-height:150px;padding:20px!important}body[data-device="desktop"] #learningCommandBtn{min-height:54px;font-size:15px}body[data-device="desktop"] #workbenchOverviewBtn,body[data-device="desktop"] #uiSettingsBtn{grid-column:span 6!important;min-height:42px}body[data-device="desktop"] .bottom .nav span{font-size:22px!important}body[data-device="desktop"] .bottom .nav{gap:2px;border:1px solid transparent}body[data-device="desktop"] .bottom .nav.on{border-color:color-mix(in srgb,var(--a) 20%,transparent)}
`;
let s=document.createElement('style');s.id='visualPolishStyle';s.textContent=css;document.head.appendChild(s);
function tidy(){let d=document.getElementById('dashboard');if(!d)return;let cmd=document.getElementById('learningCommandBtn');if(cmd){cmd.innerHTML='<span style="font-size:18px">⌁</span>&nbsp; 学习总览';cmd.title='查看今天的学习重点、任务与长期学习线'}let status=document.getElementById('workbenchOverviewBtn');if(status){status.textContent='数据与状态';status.title='备份、同步和运行状态'}let set=document.getElementById('uiSettingsBtn');if(set){set.textContent='界面设置';set.title='切换手机、平板、电脑布局'}}
const old=window.renderDashboard;window.renderDashboard=function(){let r=old&&old.apply(this,arguments);setTimeout(tidy,0);return r};setTimeout(tidy,600);
})();